theme: jekyll-theme-cayman
title: "Hire me? Please?"
description: "Casual blog description: Blogging about Software Development and technologies generally. I build software from scratch using variety of technologies and I write about it. Feel free to contact me with anything at jakub.heyduk@bitsolutions.cz" 
